name: SQA CI Demo

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  validate-and-verify:
    runs-on: ubuntu-latest

    steps:
      - name: Run Validation
        run: python scripts/validate.py

      - name: Run Verification
        run: python scripts/verify.py


